package org.example.project1.entity;

public enum BotStep {
    NONE,
    START,
    SEND_PHONE,
    WAITING_FOR_PASSWORD,
    ADMIN_MENU,
    ADD_USER_NAME,
    ADD_USER_PHONE,
    ADD_USER_PASSWORD,
    ADD_USER_SELECT_SUBSCRIPTION_TYPE,
    ADD_USER_DAY_COUNT,
    ADD_SUBSCRIPTION_TYPE_NAME,
    ADD_SUBSCRIPTION_TYPE_PRICE,
    ADD_SUBSCRIPTION_TYPE_DURATION,
    ADD_SUBSCRIPTION_TYPE_DAYCOUNT,
    ADD_SUBSCRIPTION_TYPE_DESCRIPTION,
    EDIT_SUBSCRIPTION_TYPE_NAME,
    EDIT_SUBSCRIPTION_TYPE_PRICE,
    EDIT_SUBSCRIPTION_TYPE_DURATION,
    EDIT_SUBSCRIPTION_TYPE_DESCRIPTION,
    EDIT_USER_NAME,
    EDIT_USER_PHONE,
    EDIT_USER_SELECT_SUBSCRIPTION_TYPE,
    EDIT_USER_DAY_COUNT,
    WAITING_FOR_REPORT_TYPE,
    ADD_DAY_SELECT_USER
}
